---
- name: Provision Gitlab Demo
  hosts: gitlab
  become: true
  gather_facts: yes
  vars_files:
    - vars/main.yml
  vars:
    skip_remote: true

  roles:
    # setup hosts-file on your local machine for convenience
    - role: hosts-file

    # install gitlab
    - role: geerlingguy.gitlab

    # set admin password and reconfigure
    - role: gitlab-post-config

    # import projects into gitlab
    - role: gitlab-import
      tags: gitlab_import

- name: Provision Gitlab runner demo
  hosts: gitlab-runner
  become: true
  gather_facts: yes
  vars_files:
    - vars/main.yml
  vars:
    skip_remote: true
  roles:
    # setup hosts-file on your local machine for convenience
    - role: hosts-file

    # obtain the runnger token from gitlab
    - role: gitlab-runner-token
      delegate_to: gitlab

    - role: copy-gitlab-ssl

    - role: riemers.gitlab-runner

    - role: ansible-lint

    - role: molecule

- name: Provision Tower Demo
  hosts: ansible-tower
  become: true
  gather_facts: no
  vars_files:
    - vars/main.yml
  roles:
    # setup hosts-file on your local machine for convenience
    - role: hosts-file

    - role: tower
      tags: tower_install

    - role: tower_build
      tags: tower_build
