---

- gitlab_project:
    name: "{{gitlab_import_project}}"
    group: AutomationContent
    visibility: public
    state: present
  register: gitlab_project_info

- name: move over {{gitlab_import_project}}
  synchronize:
    src: "{{gitlab_import_project}}"
    #not ideal but we're using vagrant so we know home dir is set
    dest: /tmp

- name: ensure gitlab is a known host
  shell: "{{item}}"
  with_items:
  - "touch ~/.ssh/known_hosts"
  - "ssh-keyscan gitlab >> ~/.ssh/known_hosts"

- name: add and commit all files for {{gitlab_import_project}}
  shell: >
    git config --global user.name 'root';
    git config --global user.email 'root@gitlab';
    git remote | grep -s origin && git remote add origin {{gitlab_project_info.project.ssh_url_to_repo}};
    git add -A .;
    git status -s | grep -s '' && git commit -m 'initial cut';
    git push -u origin master;
  args:
    chdir: "/tmp/{{gitlab_import_project}}"
    
  ignore_errors: yes
